# ************************ #
# Repository settings.
# ************************ #


# == Top-level settings ========================================================

repository:
  name: DjangOps
  description: "A lean DevOps inspired template for perfectionists, with deadlines."
  homepage: https://github.com/apexDev37/DjangOps
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_discussions: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  has_security_advisories: true
  default_branch: main

# == Label settings ============================================================

labels:
  - name: "good first issue"
    color: 7057ff
    description: "Issues ideal for first-time contributors"
  - name: "help wanted"
    color: 008672
    description: "Issues where community help is needed"
  - name: "bug"
    color: d73a4a
    description: "Something isn't working"
  - name: "enhancement"
    color: a2eeef
    description: "New feature or request"
  - name: "documentation"
    color: 0075ca
    description: "Improvements or additions to documentation"
  - name: "question"
    color: d876e3
    description: "Further information is requested"
  - name: "wontfix"
    color: ffffff
    description: "This will not be worked on"
  - name: "duplicate"
    color: cfd3d7
    description: "This issue or pull request already exists"
  - name: "invalid"
    color: e4e669
    description: "This doesn't seem right"

# == Branch settings ===========================================================

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
      enforce_admins: true
      required_pull_request_reviews:
        dismissal_restrictions:
          users: []
          teams: []
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions:
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

# == Collaborator settings =====================================================

collaborators:
  - username: ""
    permission: admin
  - username: ""
    permission: write
