---
failure-threshold: info
label-schema:
  author: text
  contact: email
  version: semver
  license: spdx
no-color: false
no-fail: false
strict-labels: true
disable-ignore-pragma: false
trustedRegistries:
  - docker.io
  - "*.gcr.io"
ignored:
  - DL3049
