fail_fast: false
repos:
  # Best Practices
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      -   id: check-builtin-literals
      -   id: check-executables-have-shebangs
      -   id: check-json
      -   id: check-symlinks
      -   id: check-yaml
      -   id: debug-statements
      -   id: detect-private-key
      -   id: end-of-file-fixer
      -   id: name-tests-test
          args: [--pytest-test-first]
      -   id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]

  # Formatting
  -   repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
      -   id: black

  -   repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
      -   id: isort
          args: [
            '--settings-path', 'pyproject.toml',
            '/src',
            '/tests',
            '/test_utils',
          ]

  -   repo: https://github.com/maxwinterstein/shfmt-py
      rev: v3.7.0.1
      hooks:
      -   id: shfmt

  # Linting
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.8
      hooks:
      -   id: ruff
          args: [--fix]
          exclude: ^(test_utils/|migrations/|setup\.py)$

  -   repo: https://github.com/AleksaC/hadolint-py
      rev: v2.12.1b3
      hooks:
      -   id: hadolint
          args: [--config, .hadolint.yaml]

  -   repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
      -   id: shellcheck

  # Code Quality
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      -   id: mypy
          args: [--config-file, pyproject.toml, --warn-unused-configs]

  # Security
  -   repo: https://github.com/PyCQA/bandit
      rev: 1.7.8
      hooks:
      -   id: bandit
          args: [-c, pyproject.toml, -r]
          additional_dependencies: ["bandit[toml]"]

  # Documentation, Spelling
  -   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.16.0
      hooks:
      -   id: commitlint
          stages: [commit-msg]
          additional_dependencies: ['@commitlint/config-conventional']

  -   repo: https://github.com/igorshubovych/markdownlint-cli
      rev: 'v0.41.0'
      hooks:
      -   id: markdownlint
          args: ['-f']

  -   repo: https://github.com/codespell-project/codespell
      rev: v2.3.0
      hooks:
      -   id: codespell
          files: \.(py|sh|md|rst|yml|yaml)$
