---
include:
  - path: db/local-admin.yaml
    project_directory: .

services:
  web:
    image: djangops:dev
    build:
      args:
        - TARGET=develop
      target: local-runtime
    container_name: django_web_dev
    restart: unless-stopped
    extends:
      file: docker/compose/fragments/watch-spec.yaml
      service: develop.watch
    ports: !override
      - name: web-insecure
        target: 8000
        host_ip: 127.0.0.1
        published: "8001"
        protocol: tcp
        app_protocol: http

  db:
    networks:
      - admin-back-tier
