---
include:
  - path: db/local-admin.yaml
    project_directory: .

services:
  web:
    image: djangops:dev
    build:
      target: env-develop
    container_name: django_web_dev
    restart: unless-stopped
    extends:
      file: docker/compose/fragments/watch-spec.yaml
      service: develop.watch

  db:
    networks:
      - admin-back-tier
