---
include:
  - path: db/storage.yaml
    project_directory: .

services:
  web:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: django_web
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - ./docker
            - ./tests
            - ./test_utils
        - action: rebuild
          path: ./requirements/base.txt
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
      - django-secret-key
    networks:
      - front-tier
      - back-tier
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db-password
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
    env_file:
      - path: ./.envs/django.env
        required: true
      - path: ./.envs/database.env
        required: true

networks:
  front-tier: {}

secrets:
  django-secret-key:
    file: docker/secrets/secret_key.txt
