---
include:
  - path: db/local-admin.yaml
    project_directory: .

services:
  web:
    image: djangops:test
    build:
      args:
        - TARGET=testing
      target: local-runtime
    container_name: django_web_test
    restart: unless-stopped
    extends:
      file: docker/compose/fragments/watch-spec.yaml
      service: testing.watch
    ports: !reset
      - name: web-insecure
        target: 8000
        host_ip: 127.0.0.1
        published: "8002"
        protocol: tcp
        app_protocol: http

  db:
    networks:
      - admin-back-tier
