---
include:
  - path: db/storage.yaml
    project_directory: .
  - path: db/secrets.yaml
    project_directory: .

services:
  web:
    image: djangops:base
    build:
      context: .
      dockerfile: src/Dockerfile
      target: final-stage
    container_name: django_web
    restart: no
    depends_on:
      db:
        condition: service_healthy
        required: true
    extends:
      file: db/config/connection-params.yaml
      service: web.interface
    secrets:
      - source: django-secret-key
        target: secret_key
        uid: "1000"
        gid: "101"
        mode: 0400
    networks:
      - front-tier
      - back-tier
    ports:
      - name: web-insecure
        target: 8000
        host_ip: 127.0.0.1
        published: "8080"
        protocol: tcp
        app_protocol: http
    environment:
      - SECRET_KEY_FILE=/run/secrets/secret_key
    env_file:
      - path: .envs/django.env
        required: true
      - path: .envs/database.env
        required: true

networks:
  front-tier: {}

secrets:
  django-secret-key:
    file: docker/secrets/secret_key.txt
