---
version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - ./:/usr/src/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env

networks:
  app_network:
