.PHONY: clean clean_tox envs help requirements secrets selfcheck upgrade uv

.DEFAULT_GOAL := help

# --------------------------------------------------------------------------------------
# Base
# --------------------------------------------------------------------------------------

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -rf build/
	rm -rf dist/
	rm -rf *.egg-info

clean_tox: ## clear tox requirements cache
	rm -fr .tox

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

# --------------------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------------------

export UV_REQUEST_TIMEOUT ?= 60

uv: ## install pinned version of uv
	python3 -m pip install -qU pip
	python3 -m pip install -qr requirements/uv.txt

UV_COMPILE_OPTS = --quiet --upgrade
UV_COMPILE = uv pip compile $(UV_COMPILE_OPTS)
# Omit build-related tools and packages from the compiled output.
UV_COMPILE_UNSAFE = $(UV_COMPILE) \
	--no-emit-package pip \
	--no-emit-package setuptools \
	--no-emit-package wheel

# [Important] Order requirements based on their include layer hierarchy!
REQUIREMENTS_GROUPS := pip uv base ci test-ci prod test quality dev

upgrade: export UV_CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: uv ## upgrade requirements/*.txt files with the latest packages satisfying requirements/*.in
	@for group in $(REQUIREMENTS_GROUPS); do \
		echo "Upgrading requirements/$$group.in -> requirements/$$group.txt"; \
		CMD=$$( [ "$$group" = "pip" ] && echo "$(UV_COMPILE)" || echo "$(UV_COMPILE_UNSAFE)" ); \
		$$CMD -o requirements/$$group.txt requirements/$$group.in; \
	done

requirements: clean_tox uv ## sync active environment with dev (all) requirements
	uv pip sync -q requirements/dev.txt

# --------------------------------------------------------------------------------------
# Setup
# --------------------------------------------------------------------------------------

# Shell func to provide standard info output on automated file generation.
define output_generate_info_msg
	if [ -n "$(3)" ]; then \
		echo "Generated the following $(1) files from $(2) files: $(3)"; \
	fi
endef

# Find all example env files in the project.
EXAMPLE_ENV_FILES := $(shell find . -type f -name "*.env.example")

envs: ## generate env files required to configure application environment
	@generated_files=""; \
	for file in $(EXAMPLE_ENV_FILES); do \
		env_name=$$(basename "$$file" | sed -e 's/\.env\.example$$//'); \
		target_file="$$(dirname "$$file")/$$env_name.env"; \
		if [ ! -e "$$target_file" ]; then \
			cp "$$file" "$$target_file"; \
			generated_files="$$generated_files\n- $$target_file"; \
		fi \
	done; \
	$(call output_generate_info_msg,"env","example",$$generated_files)

# Find all placeholder secret files in the project.
PLACEHOLDER_FILES := $(shell find . -type f -path "*/secrets/*" -name "*.txt.sample")

# Patterns for secret file names to generate for a secure secret value.
SECRET_NAME_PATTERN_RE := 'key|secret|password'

# Shell func to populate a file with a random, cryptographic, base64-encoded value.
define generate_random_secret
	if echo "$1" | grep -qE $(SECRET_NAME_PATTERN_RE); then \
		if [[ "$1" == "db_password" ]]; then \
			openssl rand -base64 64 | tr -dc '[:alnum:]' > "$2"; \ # URL-safe
		else \
			openssl rand -base64 64 | tr -d '\n' > "$2"; \
		fi \
	fi
endef

secrets: ## generate secrets required by Compose application model
	@generated_files=""; \
	for file in $(PLACEHOLDER_FILES); do \
		secret_name=$$(basename "$$file" | sed -e 's/\.txt.sample$$//'); \
		target_file="$$(dirname "$$file")/$$secret_name.txt"; \
		if [ ! -e "$$target_file" ]; then \
			touch "$$target_file"; \
			$(call generate_random_secret,$$secret_name,$$target_file); \
			generated_files="$$generated_files\n- $$target_file"; \
		fi \
	done; \
	$(call output_generate_info_msg,"secret","placeholder",$$generated_files)
