---
x-common-src: &src-sync-watch
  action: sync
  path: ../../../src
  target: /usr/src/app/src

x-common-tests: &tests-sync-watch
  action: sync
  path: ../../../tests
  target: /usr/src/app/tests

x-common-test-utils: &tests_utils-sync-watch
  action: sync
  path: ../../../test_utils
  target: /usr/src/app/test_utils

x-common-tools: &tools-sync-watch
  action: sync
  path: ../../../pyproject.toml
  target: /usr/src/app/pyproject.toml

x-common-tox: &tox-sync-watch
  action: sync
  path: ../../../tox.ini
  target: /usr/src/app/tox.ini

x-common-settings: &settings-restart-watch
  action: sync+restart
  path: ../../../src/config/settings
  target: /usr/src/app/config/settings

services:
  develop.watch:
    develop:
      watch:
        - *src-sync-watch
        - *tests-sync-watch
        - *tests_utils-sync-watch
        - *tools-sync-watch
        - *tox-sync-watch
        - *settings-restart-watch
        # Include additional, custom sequences for watch actions.
        - action: rebuild
          path: ../../../requirements/dev.txt

  testing.watch:
    develop:
      watch:
        - *src-sync-watch
        - *tests-sync-watch
        - *tests_utils-sync-watch
        - *tools-sync-watch
        - *tox-sync-watch
        - *settings-restart-watch
        # Include additional, custom sequences for watch actions.
        - action: rebuild
          path: ../../../requirements/test.txt
