---
services:
  db.interface:
    secrets:
      - source: db-name
        target: db-name
        uid: "1000"
        gid: "101"
        mode: 0400
      - source: db-password
        target: db-password
        uid: "1000"
        gid: "101"
        mode: 0400
      - source: db-user
        target: db-user
        uid: "1000"
        gid: "101"
        mode: 0400
    environment:
      - DB_NAME_FILE=/run/secrets/db-name
      - DB_PASSWORD_FILE=/run/secrets/db-password
      - DB_USER_FILE=/run/secrets/db-user

  web.interface:
    extends: db.interface
    secrets:
      - source: db-host
        target: db-host
        uid: "1000"
        gid: "101"
        mode: 0400
    environment:
      - DB_HOST_FILE=/run/secrets/db-host
