---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - ./docker
            - ./tests
            - ./test_utils
        - action: rebuild
          path: ./requirements/base.txt
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
      - django-secret-key
    networks:
      - front-tier
      - back-tier
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db-password
      - SECRET_KEY_FILE=/run/secrets/django-secret-key
    env_file:
      - path: ./.envs/django.env
        required: true

  db:
    image: postgres:16.2
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    env_file:
      - path: ./.envs/postgres.env
        required: true
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  front-tier: {}
  back-tier: {}

secrets:
  db-password:
    file: db/db_password.txt
  django-secret-key:
    file: docker/secrets/secret_key.txt
