---
services:
  adminer:
    image: adminer:latest
    container_name: db_admin_gui
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=galkaev
    profiles: [admin]
    networks:
      - admin-back-tier
    ports:
      - "127.0.0.1:8080:8080"

networks:
  admin-back-tier: {}
