---
x-db-conn:
  secrets: &database-connection-secrets
    - db-host
    - db-name
    - db-password
    - db-user

x-db-env:
  environment: &database-environment-secrets
    - POSTGRES_DB_FILE=/run/secrets/db-name
    - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    - POSTGRES_USER_FILE=/run/secrets/db-user

services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: postgres_db
    restart: unless-stopped
    shm_size: 128mb
    user: postgres
    secrets: *database-connection-secrets
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
    expose:
      - 5432
    environment: *database-environment-secrets
    env_file:
      - path: .envs/postgres.env
        required: false
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -d $(cat /run/secrets/db-name) -U $(cat /run/secrets/db-user)"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  back-tier: {}

secrets:
  db-host:
    file: db/secrets/db_host.txt
  db-name:
    file: db/secrets/db_name.txt
  db-password:
    file: db/secrets/db_password.txt
  db-user:
    file: db/secrets/db_user.txt
