---
services:
  db:
    image: postgres:16.2
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    user: postgres
    secrets:
      - db-name
      - db-password
      - db-user
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
    expose:
      - 5432
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER_FILE=/run/secrets/db-user
    env_file:
      - path: .envs/postgres.env
        required: false
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  back-tier: {}

secrets:
  db-host:
    file: db/secrets/db_host.txt
  db-name:
    file: db/secrets/db_name.txt
  db-password:
    file: db/secrets/db_password.txt
  db-user:
    file: db/secrets/db_user.txt
