---
name: Set Up Python
description: Sets up Python and installs CI dependencies
inputs:
  python-version:
    description: The Python version to set up
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install package manager
      run: python3 -m pip install -r requirements/uv.txt
      shell: bash
    - name: Install CI dependencies
      run: python3 -m uv pip install --system --no-cache -r requirements/ci.txt
      shell: bash
