---
  name: Python QA
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - "**"

  jobs:
    lint:

      name: Linting
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os:
            - ubuntu-latest
          python-version:
            - "3.12"
          toxenv:
            - lint-py

      steps:
        - uses: actions/checkout@v4
        - name: Set up Python CI
          uses: ./.github/actions/setup-python-ci
          with:
            python-version: ${{ matrix.python-version }}

        - name: Run Checks
          env:
            TOX_ENV: ${{ matrix.toxenv }}

          run: tox run
