---
  name: Python QA
  on:
    push:
      branches:
        - main
      paths:
        - 'src/**'
        - 'requirements/**'
        - 'tests/**'
        - 'test_utils/**'
        - '.github/workflows/test.yaml'

    pull_request:
      branches:
        - "**"
      paths:
        - 'src/**'
        - 'requirements/**'
        - 'tests/**'
        - 'test_utils/**'
        - '.github/workflows/test.yaml'

  jobs:
    test:

      name: Testing
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os:
            - ubuntu-latest
          python-version:
            - "3.12"
          toxenv:
            - django42
            - django50

      services:
        postgres:
          image: postgres:17.5-alpine3.22
          ports:
            - 5432:5432
          options: >-
            --health-cmd="pg_isready -U postgres"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
          env:
            POSTGRES_DB: ${{ secrets.DB_NAME }}
            POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
            POSTGRES_USER: ${{ secrets.DB_USER }}

      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Set up Python CI
          uses: ./.github/actions/setup-python-ci
          with:
            python-version: ${{ matrix.python-version }}

        - name: Run Tests
          env:
            TOX_ENV: ${{ matrix.toxenv }}

            # env variables.
            ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
            DB_ENGINE: ${{ vars.DB_ENGINE }}
            DB_HOST: ${{ vars.DB_HOST }}
            DB_PORT: ${{ vars.DB_PORT }}
            DEBUG: ${{ vars.DEBUG }}
            ENVIRONMENT: ${{ vars.ENVIRONMENT }}
            # secrets variable.
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_USER: ${{ secrets.DB_USER }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}

          run: tox run
